- name: Wolf
  weight: 50
  max_num: 30
  movement_speed: 3
  satiation: 8
  icon: ğŸº
- name: Boa
  weight: 15
  max_num: 30
  movement_speed: 1
  satiation: 3
  icon: ğŸ
- name: Fox
  weight: 8
  max_num: 30
  movement_speed: 2
  satiation: 2
  icon: ğŸ¦Š
- name: Bear
  weight: 500
  max_num: 5
  movement_speed: 2
  satiation: 80
  icon: ğŸ»
- name: Eagle
  weight: 6
  max_num: 20
  movement_speed: 3
  satiation: 1
  icon: ğŸ¦…
- name: Horse
  weight: 400
  max_num: 20
  movement_speed: 4
  satiation: 60
  icon: ğŸ´
- name: Deer
  weight: 300
  max_num: 20
  movement_speed: 4
  satiation: 50
  icon: ğŸ¦Œ
- name: Rabbit
  weight: 2
  max_num: 150
  movement_speed: 2
  satiation: 0.45
  icon: ğŸ‡
- name: Mouse
  weight: 0.05
  max_num: 500
  movement_speed: 1
  satiation: 0.01
  icon: ğŸ
- name: Goat
  weight: 60
  max_num: 140
  movement_speed: 3
  satiation: 10
  icon: ğŸ
- name: Sheep
  weight: 70
  max_num: 140
  movement_speed: 3
  satiation: 15
  icon: ğŸ‘
- name: Boar
  weight: 400
  max_num: 50
  movement_speed: 2
  satiation: 50
  icon: ğŸ—
- name: Buffalo
  weight: 700
  max_num: 10
  movement_speed: 3
  satiation: 100
  icon: ğŸ¦¬
- name: Duck
  weight: 1
  max_num: 200
  movement_speed: 4
  satiation: 0.15
  icon: ğŸ¦†
- name: Caterpillar
  weight: 0.01
  max_num: 1000
  movement_speed: 0
  satiation: 0
  icon: ğŸ›
- name: Frog
  weight: 0.5
  max_num: 200
  movement_speed: 1
  satiation: 0.05
  icon: ğŸ¸
- name: Banana
  weight: 0.2
  max_num: 1000
  icon: ğŸŒ
- name: Coconut
  weight: 1.5
  max_num: 500
  icon: ğŸ¥¥
- name: Palm
  weight: 100
  max_num: 50
  icon: ğŸŒ´
- name: Grass
  weight: 0.1
  max_num: 10000
- name: Grass
  weight: 0.1
  max_num: 10000
  icon: ğŸŒ¿
- name: Pitcher
  weight: 0.02
  max_num: 1000
  icon: ğŸ¥€